credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM # Not available in pipelines
              id: "jenkins-agent-ssh-key"
              username: "jenkins" # Default agent name
              description: "SSH private key used to connect to the associated agent"
              privateKeySource:
                directEntry:
                  privateKey: ${SSH_AGENT_KEY} # From the secret mounted by docker-compose in this container in /run/secrets/SSH_AGENT_KEY
          - usernamepassword:
              description: "Jenkins GitHub API token"
              id: "github-api-token"
              scope: GLOBAL
              username: "github"
              password: ${GITHUB_API_TOKEN}
          - usernamepassword:
              description: "Unity Account"
              id: "unity-account"
              scope: GLOBAL
              username: ${UNITY_USERNAME}
              password: ${UNITY_PASSWORD}