jenkins:
  systemMessage: |
    Welcome to our build server.

    This Jenkins is 100% configured and managed 'as code'.
    Config is now mostly handled by 'Jenkins Configuration as Code Plugin' (JCasC).
    JCasC config can be found in the jenkins.yaml file in the $JENKINS_HOME/casc/ folder.

    some settings are still injected from init.groovy.d scripts,
    but these settings will be ported over to JCasC as support becomes available.
  securityRealm:
    local:
# No link to sign up
      allowsSignup: false
      users:
        - id: "admin"
          password: "butler"
  authorizationStrategy: loggedInUsersCanDoAnything
  globalNodeProperties:
    - envVars:
        env:
          - key: "PUBLIC_IP"
            value: "${PUBLIC_IP}"
  numExecutors: 0
unclassified:
  location:
    url: "${JENKINS_EXT_URL}"