#  docker compose up -d --build --force-recreate
services:

    jenkins:
        container_name: jenkins
        build: ./jenkins
        restart: always
        ports:
            - "8080:8080"
            - "50000:50000" 
        volumes:
            - jenkins-data:/var/jenkins_home:rw
            - ./jenkins/casc.d:/var/jenkins_home/casc.d/:ro
            - ./jenkins/secrets/id_jenkins.pem:/run/secrets/SSH_AGENT_KEY:ro
        environment:
            - JENKINS_EXT_URL=http://localhost:8080 
            - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.d/
            - org.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true
            - PUBLIC_IP
            - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
            - UNITY_USERNAME=${UNITY_USERNAME}
            - UNITY_PASSWORD=${UNITY_PASSWORD}
        networks:
            - automation-network

    jenkins-agent:
        container_name: jenkins-agent
        platform: linux/amd64
        build: ./agent
        restart: unless-stopped
        privileged: true
        expose: 
            - 22
        volumes:
            - agent-data:/home/jenkins:rw
            - /var/run/docker.sock:/var/run/docker.sock:rw
        environment:
            - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpNqXQ4x7fPPUBbYPxKF77Zqq6d35iPCD2chg644OUD noone@localhost.local
        networks:
            - automation-network

    appium:     ##  this will be device-farm hub (appium)
        container_name: appium
        platform: linux/amd64
        build: ./appium
        restart: unless-stopped
        privileged: true
    #    depends_on:
    #        - android-emulator
        volumes:
            - /dev/bus/usb:/dev/bus/usb
            - /home/tim/.android:/root/.android
        ports:
            - "4723:4723"
        environment: 
            - REMOTE_ADB=true
    #        - ANDROID_DEVICES=android-emulator:5555
            - REMOTE_ADB_POLLING_SEC=60
            - APPIUM_ADDITIONAL_PARAMS=-ka 800 --use-plugins=device-farm,appium-dashboard -pa /wd/hub --plugin-device-farm-platform=android
        networks:
            - automation-network

    #android-emulator:
    #    container_name: android-emulator
    #    platform: linux/amd64
    #    image: us-docker.pkg.dev/android-emulator-268719/images/28-playstore-x64:30.1.2
    #    privileged: true
    #    ports:
    #        - "5555:5555"
    #        - "8555:8555"
    #    volumes:
    #        - ~/.android:/root/.android
        #environment: 
        #    - ADBKEY=       ##  this will auth the device with the adb server 

    connection-bridge:
        container_name: connection-bridge
        build: ./connection_bridge
        ports: 
           - "8081:8080"
        networks:
            - automation-network

    cloudflared:
        container_name: cloudflared
        image: cloudflare/cloudflared:latest
        restart: unless-stopped
        command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
        networks:
            - automation-network

volumes:
    jenkins-data:
    agent-data:

networks:
  automation-network: 
